{% set name = "csxtools" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b7597916bf219778b12662d21ee24bfc635b29c66a95b85c5e252aba6ea16fc

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
  host:
    - python
    - pip
    - numpy
  run:
    - python
    - databroker
    - ipython
    - ipywidgets
    - matplotlib-base
    - pims >=0.3.3
    - tzlocal
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csxtools
    - csxtools.ext
    - csxtools.ext.fastccd
    - csxtools.ext.image
    - csxtools.ext.phocount

about:
  home: https://github.com/NSLS-II-CSX/csxtools
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Useful Python tools for NSLS-II CSX (23-ID-1) beamline
  doc_url: http://nsls-ii-csx.github.io/csxtools
  dev_url: https://github.com/NSLS-II-CSX/csxtools

extra:
  recipe-maintainers:
    - mrakitin
    - conda-forge/event-model
